import { StoryFn, Meta } from "@storybook/react";
import { PageDID as PD } from "./PageDID";

import { DIDSearchQuery } from "@/lib/infrastructure/data/view-model/createRule";

export default {
    title: "Components/Pages/PageDID",
    component: PD,
} as Meta<typeof PD>;

const Template: StoryFn<typeof PD> = (args) => <PD {...args} />;
export const PageDID = Template.bind({});
PageDID.args = {
    didMeta: {
        "name": "dataset-YSytZjXJMdiCsSiiUwXx",
        "scope": "Lawrence.Myers",
        "account": "Lawrence_Myers",
        "did_type": "Dataset",
        "created_at": new Date(2021, 3),
        "updated_at": new Date(2022, 10),
        "availability": "Deleted",
        "obsolete": false,
        "hidden": true,
        "suppressed": true,
        "purge_replicas": true,
        "monotonic": true,
        "is_open": true,
        "adler32": null,
        "guid": null,
        "md5": null,
        "filesize": null
    },
    fromDidList: "yosearch",
    // Parent DIDs [FILE]
    didParentsSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didParentsResponse: {
        data: [
            { "scope": "user.JonathanPerry", "name": "container-CiFhxTRuwjdvaQQeELSz", "did_type": "Container" },
            { "scope": "user.KristenRoberts", "name": "container-FBhdaoLCaXWGhkITdZDo", "did_type": "Container" },
            { "scope": "user.LindsayCunningham", "name": "container-sjtligDkHFzCvTlHHViB", "did_type": "Container" },
            { "scope": "user.MichelleNelson", "name": "container-ywVaczrfQxnWBKlSWdHS", "did_type": "Dataset" },
            { "scope": "user.ElizabethWong", "name": "dataset-NOKpAdZHtZJGWXUJZgLL", "did_type": "Container" },
            { "scope": "user.JasonThompson", "name": "dataset-HvjKaFsxdEfFgtPwJsVN", "did_type": "Container" },
            { "scope": "user.RobertLewis", "name": "container-ArwcGlrcDYGmQQrUFjvX", "did_type": "Container" },
            { "scope": "user.TammyWilson", "name": "dataset-VYTPOCwsECetZENrtvET", "did_type": "Container" },
            { "scope": "user.EmilyPatterson", "name": "container-DuEUODGkTvhhWsoLOZGz", "did_type": "Dataset" },
            { "scope": "user.BethMontes", "name": "dataset-fFFmkKdGzwrCnZxcgfva", "did_type": "Container" },
            { "scope": "user.MicheleLee", "name": "container-yDaHisaijzWyJPDCmYKn", "did_type": "Dataset" },
            { "scope": "user.RyanJenkins", "name": "container-CdWbKaqikyBXDsVhuFps", "did_type": "Dataset" },
            { "scope": "user.StephanieRice", "name": "container-lNDVuIPsuUMZuTonUszn", "did_type": "Dataset" },
            { "scope": "user.DennisMejia", "name": "dataset-kYUROcXgfgMlqqhPTzUL", "did_type": "Container" },
            { "scope": "user.RachelMunoz", "name": "dataset-FhBstRFhkQpothGBrmvZ", "did_type": "Dataset" },
            { "scope": "user.ZacharyPeterson", "name": "container-LllblDRkBkhikKgvibLy", "did_type": "Container" },
            { "scope": "user.NicholasMoore", "name": "container-OBWskIpfjLsXcuwUljeA", "did_type": "Container" },
            { "scope": "user.NathanMartin", "name": "container-xjeeufdwZfyXZFTNLnwK", "did_type": "Dataset" },
            { "scope": "user.ValerieBrown", "name": "dataset-zmNgBZUyeBPgnzgsyXuA", "did_type": "Dataset" },
            { "scope": "user.DennisPrice", "name": "dataset-SzdvUGoaSwwRIPpYRoNi", "did_type": "Dataset" },
            { "scope": "user.BonnieKing", "name": "dataset-DCdMCvRVEKBRfDnyGNmM", "did_type": "Container" },
            { "scope": "user.JustinKirby", "name": "dataset-muYJhMUhfbXbOORnPsho", "did_type": "Container" },
            { "scope": "user.PamelaRobbins", "name": "container-bAoZCwskmlyRFInaMxYt", "did_type": "Dataset" },
            { "scope": "user.CatherineSpencer", "name": "container-TAUKSbZyGLNKVrLJlVIW", "did_type": "Container" },
            { "scope": "user.SophiaHarris", "name": "dataset-cozvFMvuuHyFVnAKHboi", "did_type": "Dataset" },
            { "scope": "user.LisaAllen", "name": "dataset-HcndjXlpgWKFeMbBeDql", "did_type": "Container" },
            { "scope": "user.ChristopherFlowers", "name": "dataset-ZQiLbIEGqJCFArddilDf", "did_type": "Container" },
            { "scope": "user.KarenRusso", "name": "container-wnWKmRiByhbGlhKwZUiy", "did_type": "Dataset" },
            { "scope": "user.BrittneyMejia", "name": "dataset-oBqmQaHdqpjkJtKaWOJE", "did_type": "Dataset" },
            { "scope": "user.SuzanneSmith", "name": "dataset-UYHhwaQlAVXrjOSYjLyl", "did_type": "Container" },
            { "scope": "user.LisaRowland", "name": "dataset-KxvstUMDvvomIxCwpxky", "did_type": "Container" },
            { "scope": "user.AlexaMiller", "name": "dataset-TCcJGwSdbIJhHGjyuRAb", "did_type": "Container" },
            { "scope": "user.JohnWebb", "name": "container-zDHjDueoVabztvUdXCso", "did_type": "Container" },
            { "scope": "user.PeterBauer", "name": "dataset-hGlqlAFEFKJpUmKrZsUa", "did_type": "Container" },
            { "scope": "user.JavierRiley", "name": "dataset-RMBaYybySwUuDsUhoUpP", "did_type": "Dataset" },
            { "scope": "user.TinaSanchez", "name": "dataset-CuSbZNIWBaUJiFiZyIXJ", "did_type": "Container" },
            { "scope": "user.JohnHo", "name": "container-xesLHpwYmGLGyYLShNjB", "did_type": "Dataset" },
            { "scope": "user.DorothyVelez", "name": "dataset-XLyjjWEJZxYmBqGrEuEq", "did_type": "Dataset" },
            { "scope": "user.NatalieDickerson", "name": "container-FhoPFizJEUKTAvsZHKlZ", "did_type": "Dataset" },
            { "scope": "user.TommyReynolds", "name": "dataset-uUVenbBvzqMqgLjHNqiV", "did_type": "Container" },
            { "scope": "user.MonicaSanchez", "name": "container-tKaYFFofdbTRZlLLHJEp", "did_type": "Dataset" },
            { "scope": "user.MatthewCrawford", "name": "container-gJFkhjPsqYXcnEBHraNz", "did_type": "Dataset" },
            { "scope": "user.TroyGreer", "name": "container-dOmcBYhyvtXWmAOZaFVO", "did_type": "Container" },
            { "scope": "user.SaraWong", "name": "dataset-VTLgsxDkyeQwxXnBbwPn", "did_type": "Container" },
            { "scope": "user.NicholeChandler", "name": "container-kinqxtQnYYSuMBqiCBcl", "did_type": "Container" },
            { "scope": "user.CynthiaLewis", "name": "dataset-kxwpLEdrJsLYkrZvbxZd", "did_type": "Container" },
            { "scope": "user.JamesPratt", "name": "container-uhQVhcEDCbBogmOljKke", "did_type": "Container" },
            { "scope": "user.NicholasChase", "name": "container-VBocIpNtSkuvvbNpxhsI", "did_type": "Container" },
            { "scope": "user.MichaelBlack", "name": "container-HVzdplMhIJoKoLyeEVpT", "did_type": "Container" },
            { "scope": "user.BeverlyMitchell", "name": "dataset-FcTphEovdbHHAgkqzckp", "did_type": "Dataset" },
            { "scope": "user.RobertHogan", "name": "container-KmlbKNNBAsbnIIgiGhck", "did_type": "Container" },
            { "scope": "user.DonnaCaldwell", "name": "dataset-sLZLSijmRkKdPQQtIkTd", "did_type": "Dataset" },
            { "scope": "user.LisaLarson", "name": "dataset-UYBfijCmuTqOsEosnZiW", "did_type": "Container" },
            { "scope": "user.DanielLozano", "name": "container-YtszvcuFJkYBsPjrtEKC", "did_type": "Container" },
            { "scope": "user.JustinYang", "name": "container-VHLnVpXHKhhLCscsdLCz", "did_type": "Container" },
            { "scope": "user.ChristopherConner", "name": "container-mkxfgftGGotTbGzYidlA", "did_type": "Container" },
            { "scope": "user.RandyHoward", "name": "dataset-FUClHSeGYPraCwdkdURO", "did_type": "Container" },
            { "scope": "user.TylerRobbins", "name": "container-egZXJFbEPlhZtDESXGKP", "did_type": "Dataset" },
            { "scope": "user.RichardBaker", "name": "container-HeRnYBmVFMuoqQiQoNTg", "did_type": "Container" },
            { "scope": "user.ParkerThomas", "name": "container-SxMhJdjPpowdYnlzPJJp", "did_type": "Container" },
            { "scope": "user.StephenMcknight", "name": "container-OWwKVnMpCeWFnCamTsck", "did_type": "Container" },
            { "scope": "user.MargaretRogers", "name": "dataset-PRDcEfPsqMWBDemsbZBV", "did_type": "Container" },
            { "scope": "user.StephanieMoore", "name": "dataset-wWdqanoWyWZFmtMXONkP", "did_type": "Container" },
            { "scope": "user.AdamSolis", "name": "dataset-ZKVtNoUwhRkvBOyrkDTN", "did_type": "Container" },
            { "scope": "user.LauraClark", "name": "dataset-APEiEbweQvWuAqcZBjYX", "did_type": "Container" },
            { "scope": "user.BrandiTaylor", "name": "dataset-YoGzQvDRmjkpqhpmRNBP", "did_type": "Container" },
            { "scope": "user.KathleenLin", "name": "container-aMOZOKQoPMXbRxnIFVvq", "did_type": "Dataset" },
            { "scope": "user.GregoryBurke", "name": "container-PmrbbYgwpkLtMhKCCXTe", "did_type": "Dataset" },
            { "scope": "user.RebeccaCarter", "name": "container-RMBHQzIAcYdiDqnzjLFC", "did_type": "Dataset" },
            { "scope": "user.EvanSchneider", "name": "container-xTtElpBaggiYUfrxzDkV", "did_type": "Container" },
            { "scope": "user.JeremyPatel", "name": "dataset-HNBXPedhYFaBfittJTcQ", "did_type": "Dataset" },
            { "scope": "user.TamaraPowell", "name": "container-XziLmJOqZUtAETjfGZOa", "did_type": "Dataset" },
            { "scope": "user.LonnieJones", "name": "dataset-RGzmNpwPdqArCHIYFPUw", "did_type": "Container" },
            { "scope": "user.JulieBennett", "name": "dataset-ZUlRNGBUJmsauKBWcHas", "did_type": "Container" },
            { "scope": "user.MichaelBryant", "name": "dataset-qtfuGBAXgvHDKktNTDex", "did_type": "Container" },
            { "scope": "user.MelindaWade", "name": "dataset-uBGkqMDikoKGlmyneyyu", "did_type": "Container" },
            { "scope": "user.LoriLewis", "name": "container-jFerYByeDfHsEEzyBMDJ", "did_type": "Container" },
            { "scope": "user.HeatherBell", "name": "dataset-ZvtQGiAlSFJZNqlKczYm", "did_type": "Dataset" },
            { "scope": "user.RebeccaRowland", "name": "dataset-jiKtRyCkYIURaYkPtaXT", "did_type": "Dataset" },
            { "scope": "user.BrendaAlexander", "name": "container-UHDeQjWwxpOSrvaGOOKm", "did_type": "Container" },
            { "scope": "user.WilliamByrd", "name": "container-usIyRQICDvtJvSPbxgfe", "did_type": "Container" },
            { "scope": "user.BruceHolloway", "name": "dataset-oSwhbUWHPOmXVdaxTsbQ", "did_type": "Container" },
            { "scope": "user.SamanthaThompson", "name": "dataset-KwGGRweNamLbZjXRBhXc", "did_type": "Dataset" },
            { "scope": "user.MarieWilliams", "name": "container-OhpheVMIMCBENPLEAJxO", "did_type": "Container" },
            { "scope": "user.ReginaldLopez", "name": "container-jNOIrXMOWjcufRGmsKih", "did_type": "Container" },
            { "scope": "user.TylerCervantes", "name": "container-ePtRRjtOYgnuzEFjcXKO", "did_type": "Container" },
            { "scope": "user.YvonneBurch", "name": "container-utWSEwtYIFSRqehKsCta", "did_type": "Dataset" },
            { "scope": "user.StevenEvans", "name": "dataset-XyclDKIZIWEObsetPnUh", "did_type": "Dataset" },
            { "scope": "user.MelindaHunter", "name": "container-ObLvyUuZBBbZHmBGSNkr", "did_type": "Container" },
            { "scope": "user.KatrinaJohnson", "name": "container-CycXtGUWyBKZBoSFHkzi", "did_type": "Dataset" },
            { "scope": "user.TimothyHansen", "name": "dataset-AtEEUPYGaYRBMSdqcMKv", "did_type": "Container" },
            { "scope": "user.JanetHoffman", "name": "container-mCMgkEhBLUpduwjPSVHM", "did_type": "Dataset" },
            { "scope": "user.LuisWright", "name": "dataset-mLETNnlzHWJNhWOoVWgX", "did_type": "Container" },
            { "scope": "user.RobertSmith", "name": "container-QvMVjxggobzWZcxEBEDi", "did_type": "Dataset" },
            { "scope": "user.KevinMiller", "name": "container-MLSUueVCEfcjrfkYWpmy", "did_type": "Container" },
            { "scope": "user.BrendaRich", "name": "dataset-aKzqhsRscYRbHQpRekXp", "did_type": "Container" },
            { "scope": "user.BethanyJames", "name": "container-tMoCTdkePVTrIAjKQXLe", "did_type": "Dataset" },
            { "scope": "user.WilliamAnderson", "name": "dataset-WVGuXufUnjUPlJZSzuTz", "did_type": "Container" },
            { "scope": "user.JenniferWise", "name": "dataset-DEVVgemaOOuhMqBawUvL", "did_type": "Dataset" },
            { "scope": "user.ThomasSmall", "name": "container-YaQGxbdHDdaPRHiMTSgg", "did_type": "Container" }
        ],
        fetchStatus: "idle"
    },
    // DID Metadata
    didMetadataSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didMetadataResponse: {
        data: [
            { key: "bernd", value: "das brot" },
            { key: "kika", value: "der sender" },
            { key: "kikaninchen", value: "das tier" },
            { key: "my birthday", value: new Date(2021, 3) },
            { key: "am_i_anton", value: false },
            { key: "R1-tastefactor", value: 3.142 },
            { key: "hello", value: null },
        ],
        fetchStatus: "idle"
    },
    // Filereplicas
    didFileReplicasSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didFileReplicasResponse: {
        data: [
            { rse: "FRESNO-AWS_SCRATCHDISK", state: "Available" },
            { rse: "PRAGUELCG2_SCRATCHDISK", state: "Unavailable" },
            { rse: "BNL-OSG2_SCRATCHDISK", state: "Copying" },
            { rse: "BNL-OSG2_SCRATCHDISK", state: "Being_Deleted" },
            { rse: "BNL-OSG2_SCRATCHDISK", state: "Bad" },
            { rse: "BNL-OSG2_SCRATCHDISK", state: "Temporary_Unavailable" },
        ],
        fetchStatus: "idle"
    },
    didFileReplicasDatasetSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didFileReplicasDatasetResponse: {
        data: [
            { scope: "mc16_13TeV", name: "DAOD_EXOT12.123456784", Available: 1, Unavailable: 0, Copying: 0, Being_Deleted: 0, Bad: 0, Temporary_Unavailable: 0 },
            { scope: "mc16_14TeV", name: "DAOD_EXOT12.123456749", Available: 1, Unavailable: 1, Copying: 0, Being_Deleted: 0, Bad: 2, Temporary_Unavailable: 0 },
            { scope: "mc16_15TeV", name: "DAOD_EXOT12.123456791", Available: 0, Unavailable: 0, Copying: 0, Being_Deleted: 0, Bad: 2, Temporary_Unavailable: 1 },
            { scope: "mc15_16TeV", name: "DAOD_EXOT12.123456811", Available: 3, Unavailable: 0, Copying: 1, Being_Deleted: 1, Bad: 0, Temporary_Unavailable: 0 },
        ],
        fetchStatus: "idle"
    },
    didRulesSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didRulesResponse: {
        data: [
            { "id": "02b2007e-dbde-4dd0-ae7d-f1b71e4676d7", "name": "RULE-zTKiSFerUFaqzjsZBMXa", "state": "Suspended", "account": "user.JenniferSteele", "subscription": { "name": "KyFYeASoISJXKvvYMBlo", "account": "user.NormaConley" }, "last_modified": new Date("Fri, 05 May 2023 15:48:41 UTC") },
            { "id": "1c37891c-23b3-4922-8f6d-5132ed8fcb38", "name": "RULE-SrAaQGRrgQGxePeyhAWI", "state": "Replicating", "account": "user.RachelSmith", "subscription": { "name": "gepGcTBEYberbgbFBYso", "account": "user.MicheleValdez" }, "last_modified": new Date("Tue, 18 Apr 2023 09:29:41 UTC") },
            { "id": "b0386966-c21a-4bb2-954c-56cbb16c42e2", "name": "RULE-oBJusypGWaAfknJyShsQ", "state": "Inject", "account": "user.VictoriaDavenport", "subscription": { "name": "fskdvJYEabPKKeEwbFHL", "account": "user.JamesTaylor" }, "last_modified": new Date("Sat, 22 Apr 2023 01:02:47 UTC") },
            { "id": "9d7131cb-6641-4cc4-8861-da5545daa0d9", "name": "RULE-KakrGbMsTMFgEmdZiGFN", "state": "Suspended", "account": "user.CarrieGonzales", "subscription": { "name": "nWQcORwMJOJspVVYEmMu", "account": "user.VanessaMassey" }, "last_modified": new Date("Fri, 24 Feb 2023 17:34:13 UTC") },
            { "id": "70cded21-83c3-422e-94d5-0972a22da3fe", "name": "RULE-wIkFBWTRiCaHPaMyCmcV", "state": "Waiting_Approval", "account": "user.RebeccaRubio", "subscription": { "name": "SwyqOcAGKvtLVteGkWjc", "account": "user.FrankLarson" }, "last_modified": new Date("Tue, 28 Mar 2023 21:16:15 UTC") },
            { "id": "992b0f26-08be-473f-897c-e4c948ca4083", "name": "RULE-aYDoqNNQmizzgiPwgWPG", "state": "Inject", "account": "user.KennethLeon", "subscription": { "name": "bnwXnENCahVanDquoLEQ", "account": "user.WilliamTorres" }, "last_modified": new Date("Sun, 07 May 2023 11:04:42 UTC") },
            { "id": "7f7ee40b-9ee0-4329-8dba-4f2467a39849", "name": "RULE-cyLMQUSqCbbIQAHjStpc", "state": "OK", "account": "user.MatthewFuller", "subscription": { "name": "JzTmvcSDyAQTIZPjBmZw", "account": "user.JaredJones" }, "last_modified": new Date("Tue, 24 Jan 2023 00:32:55 UTC") },
            { "id": "5ff060a4-d596-420a-9a8a-114e8883851f", "name": "RULE-PBkDhgpegcEUMpVjpUzg", "state": "Waiting_Approval", "account": "user.DavidMarks", "subscription": { "name": "QDGwgRRWzlaohucyhjXE", "account": "user.CristinaTrujillo" }, "last_modified": new Date("Wed, 15 Mar 2023 11:36:17 UTC") },
            { "id": "a0fb8893-82ff-4250-a9d1-35d38f47ef3f", "name": "RULE-HHHeuPOGtmUjINNEoHMi", "state": "Waiting_Approval", "account": "user.DavidClark", "subscription": { "name": "tKcESqxLxbgjEXKFRVOf", "account": "user.JoannBarrett" }, "last_modified": new Date("Tue, 21 Feb 2023 00:39:56 UTC") },
            { "id": "22ccbec2-1d62-4da1-94e0-9732b51d72d7", "name": "RULE-XClxoIMONpAlggmXpfdg", "state": "OK", "account": "user.LisaHall", "subscription": { "name": "JXFpdxLPZVJhnDlOVvjL", "account": "user.NicholeWebb" }, "last_modified": new Date("Thu, 23 Feb 2023 02:56:40 UTC") },
            { "id": "b6cb3270-71e6-453f-b9f5-1df1dc5a7b1e", "name": "RULE-YeaLwMcwPgqnJDvoCQur", "state": "Stuck", "account": "user.ChristopherBailey", "subscription": { "name": "fYuwdFuscTPbwXLIQETX", "account": "user.KathrynCarr" }, "last_modified": new Date("Thu, 19 Jan 2023 16:05:15 UTC") },
            { "id": "4476c21e-ae50-4f9c-82fd-c64df7f7e619", "name": "RULE-EsvySgwaDWIwSIlPACuA", "state": "Inject", "account": "user.BrittanyMorrison", "subscription": { "name": "iBeDDrkImJozSNkVSISz", "account": "user.GaryTran" }, "last_modified": new Date("Mon, 27 Mar 2023 00:06:24 UTC") },
            { "id": "94de12c4-305e-41d4-a4fa-75e8622b58ce", "name": "RULE-YAxCMZXfjrvQgCfzCvso", "state": "Suspended", "account": "user.BenjaminSnow", "subscription": { "name": "YEPqEGIByNokpXBYzwqN", "account": "user.AngelaGarcia" }, "last_modified": new Date("Thu, 05 Jan 2023 00:38:10 UTC") },
            { "id": "37ee0f75-7f20-4671-89cd-377bb73ddaa7", "name": "RULE-PgDOMkKzdVxocUiATotn", "state": "Waiting_Approval", "account": "user.JenniferMcbride", "subscription": { "name": "NSutGcBUAREuYVTEOpND", "account": "user.TeresaRodriguez" }, "last_modified": new Date("Fri, 24 Mar 2023 11:06:46 UTC") },
            { "id": "b6294737-8053-454e-9501-568f10a15e85", "name": "RULE-dzUECkenAVqbJdcagsOK", "state": "Suspended", "account": "user.JoseLi", "subscription": { "name": "psICDmloAVmiIoUbYusP", "account": "user.AmberKent" }, "last_modified": new Date("Sat, 06 May 2023 09:34:51 UTC") },
            { "id": "27eeb5e2-454d-43a5-b869-c54c62c1dc09", "name": "RULE-JlIIjpPJPvLebYuvezIf", "state": "Waiting_Approval", "account": "user.JustinHarper", "subscription": { "name": "fYijQFpclbqWuDCdfePd", "account": "user.DavidSchwartz" }, "last_modified": new Date("Mon, 03 Apr 2023 21:54:59 UTC") },
            { "id": "42e1faed-2382-4057-8b94-aeea8e8fc7f1", "name": "RULE-TgdvhEjJWKodnqfEBlXe", "state": "Stuck", "account": "user.CindyMontoya", "subscription": { "name": "kKZrqkQXddRfFKDRifwF", "account": "user.LeahSchmitt" }, "last_modified": new Date("Sun, 26 Feb 2023 18:30:15 UTC") },
            { "id": "54601044-824e-439f-82b3-9007fa89d440", "name": "RULE-dvwSncBnPtfkGNkFbIqO", "state": "Stuck", "account": "user.ZacharyAnderson", "subscription": { "name": "sqUHPlFMbbGaqlyUtXNu", "account": "user.WillieLyons" }, "last_modified": new Date("Wed, 01 Feb 2023 03:37:45 UTC") },
            { "id": "a8a53e29-ad17-40f5-a816-310e3ff8477c", "name": "RULE-LHHTgpEaQxxYiTLDGSMC", "state": "Stuck", "account": "user.DavidMartin", "subscription": { "name": "btOkEqZZLkCRqtEbVsTP", "account": "user.AaronRay" }, "last_modified": new Date("Sat, 18 Mar 2023 21:12:02 UTC") },
            { "id": "740ebe2c-9ebf-4bea-bb22-d590b1836c7b", "name": "RULE-wACbYPFhGiAzxRBsWToL", "state": "Stuck", "account": "user.StephenFarmer", "subscription": { "name": "dFlVkYipvjxpgcCBzdYa", "account": "user.DonaldHicks" }, "last_modified": new Date("Wed, 19 Apr 2023 13:28:35 UTC") },
            { "id": "f420a11f-2ffa-4920-bb9d-9a28a2434508", "name": "RULE-RehGDEDPIbWnhdghfljh", "state": "Waiting_Approval", "account": "user.AmandaYoung", "subscription": { "name": "LRtSpHHfDHIxxUkLxRgG", "account": "user.KevinGraves" }, "last_modified": new Date("Tue, 04 Apr 2023 19:19:57 UTC") },
            { "id": "52714350-ad88-4367-bf7e-bd667241aa8a", "name": "RULE-iaPqnPFRRUFYqETgXPnI", "state": "Replicating", "account": "user.JulieRichardson", "subscription": { "name": "iGIIevJrEAPJtKGtgPRQ", "account": "user.WilliamBurke" }, "last_modified": new Date("Mon, 08 May 2023 05:10:11 UTC") },
            { "id": "c24f46fb-d07a-4e99-b735-60aa22df12c6", "name": "RULE-zTMCWXZPZFNvnobXinzg", "state": "OK", "account": "user.EmilyCrawford", "subscription": { "name": "FjgwrOzqBcIDzKBmTqZp", "account": "user.AmandaSchneider" }, "last_modified": new Date("Fri, 17 Feb 2023 22:56:18 UTC") },
            { "id": "54464bde-7f50-4274-8fe8-31d4314c3058", "name": "RULE-MzacftgGJEfvCNGILIBE", "state": "Replicating", "account": "user.SamanthaMiller", "subscription": { "name": "HoSjenJzdpGuvMFhnQmu", "account": "user.StuartStevens" }, "last_modified": new Date("Sat, 14 Jan 2023 02:04:43 UTC") },
            { "id": "fa115993-155d-40f4-ac91-a922550c0c63", "name": "RULE-BpkAWbscTEGnXaKhHQnr", "state": "Stuck", "account": "user.PaulYoung", "subscription": { "name": "ZfzwANkEDEyWbmIyejRg", "account": "user.JennyWang" }, "last_modified": new Date("Fri, 27 Jan 2023 13:13:00 UTC") },
            { "id": "78b2b65a-da9c-4fa7-8f27-90f50f644d7a", "name": "RULE-QZujWFBhFZrjjwxStKlU", "state": "OK", "account": "user.RichardAllen", "subscription": { "name": "BbswTFIAuQcpEXYxTiNw", "account": "user.MichaelSloan" }, "last_modified": new Date("Thu, 06 Apr 2023 05:00:53 UTC") },
            { "id": "45c3a58f-d44b-496b-a9df-8b08828c23b2", "name": "RULE-CmtcjDdFimuwieMtSFGn", "state": "OK", "account": "user.ErinKelly", "subscription": { "name": "oZfnsCEpBemboQBcoDBe", "account": "user.AlecClark" }, "last_modified": new Date("Mon, 06 Mar 2023 07:53:20 UTC") },
            { "id": "4d50e3a7-3b13-4577-82a5-c321f6216617", "name": "RULE-QLqOmtChAzVmHIEXZHDl", "state": "Replicating", "account": "user.JudyCisneros", "subscription": { "name": "zEApfqQVFHyBGwuKwHeS", "account": "user.EricStark" }, "last_modified": new Date("Fri, 28 Apr 2023 23:15:44 UTC") },
            { "id": "3d8132d5-2a6a-4917-8e3a-aac66edb54ff", "name": "RULE-WZNAhVImWrXvXzSwiLZG", "state": "Suspended", "account": "user.CarolynDickerson", "subscription": { "name": "GmfylmgThfwZytSCHLXc", "account": "user.RonaldCastro" }, "last_modified": new Date("Fri, 14 Apr 2023 05:25:35 UTC") },
            { "id": "1990ab00-50aa-4cdb-be9c-40bab6e31cc6", "name": "RULE-LuNaZqCKXOMFrgTkiLYT", "state": "Inject", "account": "user.JamesRoss", "subscription": { "name": "iuNzDFKndVXKHZAIujHC", "account": "user.BriannaMeadows" }, "last_modified": new Date("Thu, 05 Jan 2023 01:47:32 UTC") },
            { "id": "555fe45d-778b-43bb-8d2a-4e58a7e47436", "name": "RULE-xtnGVIbTUmyClQvWWlzZ", "state": "OK", "account": "user.BryanThomas", "subscription": { "name": "TYKBkVydajJuMKcZPWZV", "account": "user.JanetRamirez" }, "last_modified": new Date("Sun, 26 Feb 2023 08:09:16 UTC") },
            { "id": "701372ae-32cc-49f0-ac78-cf2389a3fbad", "name": "RULE-HBHAAkXrJzUVDeemRMon", "state": "OK", "account": "user.KellyProctor", "subscription": { "name": "wxqDccGHrGeCukKMRzor", "account": "user.StephenWoods" }, "last_modified": new Date("Sun, 26 Feb 2023 20:03:48 UTC") },
            { "id": "1a47b08e-3d38-4757-bf7b-4da897dd688f", "name": "RULE-oHZTGNtUWUhBNGdjynZm", "state": "Inject", "account": "user.ChristineVasquez", "subscription": { "name": "QSDIHTzXMIMsMUcAXGPf", "account": "user.AdrienneRobles" }, "last_modified": new Date("Sun, 26 Mar 2023 18:40:58 UTC") },
            { "id": "8ae2c70d-433c-46fc-aaeb-907e0d4725c8", "name": "RULE-wMQYZHCKQusPhlXUmwDI", "state": "Replicating", "account": "user.WilliamLee", "subscription": { "name": "LMkXKqFQwQTtVmHLlbLc", "account": "user.LauraGarcia" }, "last_modified": new Date("Fri, 31 Mar 2023 09:25:48 UTC") },
            { "id": "40158c42-6540-4632-adb5-a421d5879fb2", "name": "RULE-RRvwQpynKJDBvvRZdLMS", "state": "Inject", "account": "user.MichaelDudley", "subscription": { "name": "UwRAkuNkaHINoHXsYBIX", "account": "user.DeborahMiller" }, "last_modified": new Date("Sun, 09 Apr 2023 06:34:11 UTC") },
            { "id": "081e6c1a-307c-46ac-88e7-0dd90286a1a8", "name": "RULE-aWdFLezQfJtPVPScmtvP", "state": "Stuck", "account": "user.KennethDonaldson", "subscription": { "name": "jbNGLVwscNqpjEAyvbvW", "account": "user.MelissaSchmidt" }, "last_modified": new Date("Mon, 23 Jan 2023 12:35:03 UTC") },
            { "id": "f0bf8276-5140-4eb1-87aa-685774021df9", "name": "RULE-QZVxaeFlIMdkWTLygmvo", "state": "Replicating", "account": "user.GabrielJones", "subscription": { "name": "cZTWyxlmyzsDIvptztZu", "account": "user.JamesParker" }, "last_modified": new Date("Thu, 09 Mar 2023 01:09:20 UTC") },
            { "id": "dddf1c1f-45ff-4384-bca1-5ec58c852486", "name": "RULE-IKyautNZlIKydWntkPMl", "state": "Replicating", "account": "user.DanielleFerguson", "subscription": { "name": "zkmAAebjyahZKFqoKDKb", "account": "user.StephenJenkins" }, "last_modified": new Date("Sat, 08 Apr 2023 08:11:48 UTC") },
            { "id": "f4a16129-1882-4047-9369-b5fb31a827a9", "name": "RULE-SaLXsGgmyByiONKnUHXF", "state": "Inject", "account": "user.MaryWalker", "subscription": { "name": "sVfpEYnDPZnEdNmWNyMT", "account": "user.BrittanyJones" }, "last_modified": new Date("Thu, 12 Jan 2023 16:20:40 UTC") },
            { "id": "87154996-6917-4afb-baae-98d140e1c609", "name": "RULE-iXHZQAZtwMogueYKgERi", "state": "Inject", "account": "user.WilliamAndrews", "subscription": { "name": "qYypqjmCVrpYPnSZAnZA", "account": "user.AnthonyWalker" }, "last_modified": new Date("Mon, 06 Feb 2023 00:41:12 UTC") },
            { "id": "88e804e9-edc4-4f73-80ca-9833a2e861d0", "name": "RULE-RPxtaazEMKmevIRiSpdH", "state": "Inject", "account": "user.KennethGriffin", "subscription": { "name": "WBaCccaqDLxLOHNeBhrZ", "account": "user.BrendanJohnson" }, "last_modified": new Date("Tue, 11 Apr 2023 11:40:00 UTC") },
            { "id": "0b18b6da-f328-413b-9705-4b2be371fd9b", "name": "RULE-bqYeRfLcOKxFvILrmkoX", "state": "Inject", "account": "user.BarbaraFrey", "subscription": { "name": "DEJiqmkEVNXQUCNNFFaa", "account": "user.KathrynWard" }, "last_modified": new Date("Sun, 07 May 2023 06:39:01 UTC") },
            { "id": "2f90cf14-de1f-458d-b460-1279ec3c348f", "name": "RULE-chepHofeJposZqTOjvuy", "state": "Replicating", "account": "user.JoshuaPowers", "subscription": { "name": "HwEOWdjcRCsdrHOWfHJC", "account": "user.MichelleJohnson" }, "last_modified": new Date("Fri, 24 Feb 2023 07:22:06 UTC") },
            { "id": "fbe740ff-b3a5-4aa1-8dcc-56dbba1b3aa1", "name": "RULE-hbCCBbpgutGGkfBnzqJe", "state": "Replicating", "account": "user.AmberWare", "subscription": { "name": "mciBdsftzknbOtwhCEcY", "account": "user.RobertMack" }, "last_modified": new Date("Thu, 09 Mar 2023 23:26:50 UTC") },
            { "id": "a1f0388e-8c5f-4cbe-a369-35393e1ad8bc", "name": "RULE-MneIxVNRzuIPpFzgdFmE", "state": "Suspended", "account": "user.MichaelHaynes", "subscription": { "name": "sqQhTWFzUxEThkGTrjke", "account": "user.AllisonBest" }, "last_modified": new Date("Thu, 09 Mar 2023 09:49:10 UTC") },
            { "id": "519adde3-3593-4adb-beef-2a7019ee9607", "name": "RULE-rTTWdlbdulrMPyNpRHyY", "state": "Inject", "account": "user.StevenGonzalez", "subscription": { "name": "NTMrENroxQFzvTYQPRBa", "account": "user.CarolGutierrez" }, "last_modified": new Date("Wed, 29 Mar 2023 18:13:06 UTC") },
            { "id": "a7282b18-c7cc-4a92-888e-089a498a2abc", "name": "RULE-vwlHxHBhJHTtIGszUHyb", "state": "Inject", "account": "user.ChristopherDavis", "subscription": { "name": "RidfJoCWDhewZTvgcjGT", "account": "user.CliffordOconnell" }, "last_modified": new Date("Tue, 31 Jan 2023 13:38:48 UTC") },
            { "id": "4c0eb426-b9b6-41a9-a788-5583c5c48cab", "name": "RULE-yBLFnmhnsdBOdUnoFiHz", "state": "Replicating", "account": "user.KellyDickerson", "subscription": { "name": "AYYvLzpVsoTNljuMPFVS", "account": "user.DawnSchroeder" }, "last_modified": new Date("Mon, 13 Feb 2023 12:08:52 UTC") },
            { "id": "60aea9f6-ecf3-4d52-91d5-ae71f5dc5862", "name": "RULE-KFHlSfxxqyOmHroKwjpZ", "state": "OK", "account": "user.JenniferGriffin", "subscription": { "name": "JCtGGErCAFZCCowCSwhq", "account": "user.KarenBaker" }, "last_modified": new Date("Sat, 11 Mar 2023 13:24:55 UTC") },
            { "id": "bd7707c6-a887-4477-aeb4-4af45ac0c4ef", "name": "RULE-VFXjuhNPIuzWDVngfDbl", "state": "OK", "account": "user.StephanieColeman", "subscription": { "name": "kCdClYPubqnXXPCffXVh", "account": "user.BrianKrause" }, "last_modified": new Date("Fri, 14 Apr 2023 17:53:29 UTC") },
            { "id": "597518ed-fef1-48e9-ae9a-0bda0e33fcf5", "name": "RULE-XJWQiLjNJUsvkERzIkyP", "state": "Suspended", "account": "user.AdamLewis", "subscription": { "name": "MXeBAQMrvAvcuekLolLm", "account": "user.RobertWilson" }, "last_modified": new Date("Thu, 23 Mar 2023 15:12:26 UTC") },
            { "id": "72d55537-0140-4af1-9299-45550bfe4d1a", "name": "RULE-SBxjwpFSPQacnKZiOWxf", "state": "Replicating", "account": "user.EricaSerrano", "subscription": { "name": "vtoUkDxhSKIhHovvADRs", "account": "user.KylePotter" }, "last_modified": new Date("Sun, 15 Jan 2023 16:17:18 UTC") },
            { "id": "b058cfc4-1ed9-4667-bf05-9e1bf9af27aa", "name": "RULE-kQBypRjJrqYIphkVOCJX", "state": "Suspended", "account": "user.ChristinaAdams", "subscription": { "name": "LsCNvHkysyecncOsNmiR", "account": "user.KimberlyMitchell" }, "last_modified": new Date("Mon, 24 Apr 2023 11:53:01 UTC") },
            { "id": "14bad8e0-a290-4da9-9055-16b8fb3c3927", "name": "RULE-CeQFgGYNiwKlEjYiPhBv", "state": "Replicating", "account": "user.LaurenHoffman", "subscription": { "name": "chCpsffPksqcRrZpWnAe", "account": "user.MitchellMartinez" }, "last_modified": new Date("Tue, 25 Apr 2023 12:15:53 UTC") },
            { "id": "02130b76-7947-4fad-8a29-0c1cb8224562", "name": "RULE-AsihNIvChtsrqNTnPKtu", "state": "Suspended", "account": "user.RichardJones", "subscription": { "name": "oaTwEceWMQPBTfNkROuk", "account": "user.JenniferDunn" }, "last_modified": new Date("Tue, 11 Apr 2023 21:56:22 UTC") },
            { "id": "3a1e4310-830e-4157-8191-f0cc783c1c2d", "name": "RULE-iqrojlebofZiwojIpzrP", "state": "Waiting_Approval", "account": "user.JamesHudson", "subscription": { "name": "ORYKikjGBcNwejAfveQQ", "account": "user.AnnetteSimon" }, "last_modified": new Date("Fri, 24 Mar 2023 15:30:40 UTC") },
            { "id": "5d45297b-0a6a-4eff-a829-420fa75fb512", "name": "RULE-KrERgfrolpgGyScnLFoo", "state": "Suspended", "account": "user.TylerPalmer", "subscription": { "name": "gvudBCVuOtySRGBmbqFF", "account": "user.SherryCrawford" }, "last_modified": new Date("Mon, 30 Jan 2023 02:35:39 UTC") },
            { "id": "56608f51-c832-47e4-bf72-02d08b25e559", "name": "RULE-nqAftLMPOPENXKfmoaIO", "state": "OK", "account": "user.MarkMcdonald", "subscription": { "name": "hLVxVVmPChIWgVyAxCWR", "account": "user.CraigHooper" }, "last_modified": new Date("Tue, 14 Feb 2023 22:55:39 UTC") },
            { "id": "ba0c4542-69ed-43a6-af2b-a5eaa1c07431", "name": "RULE-HeNQkUaITWuarcOHmaRP", "state": "Replicating", "account": "user.AmandaBooth", "subscription": { "name": "OnvByOIOLSoSqPvHTGpl", "account": "user.TiffanyGarrett" }, "last_modified": new Date("Wed, 10 May 2023 21:45:47 UTC") },
            { "id": "751c39fe-1dd2-4484-a412-e952b36c87fa", "name": "RULE-WUBjmLDJnOBrAugpFpYs", "state": "Stuck", "account": "user.StacyGonzalez", "subscription": { "name": "pvxiYkvrpfKCNWPePyVH", "account": "user.JessicaForbes" }, "last_modified": new Date("Fri, 20 Jan 2023 17:48:51 UTC") },
            { "id": "87e0fa5d-fe69-4c6e-8191-3982e7df6f01", "name": "RULE-ZQSkrFJKUNfKAmdCLNuw", "state": "Inject", "account": "user.JulieMitchell", "subscription": { "name": "gjOkrFtRusYOibRvDvUC", "account": "user.ElizabethStephens" }, "last_modified": new Date("Sun, 30 Apr 2023 20:39:11 UTC") },
            { "id": "7ac7155c-c4d1-4ec1-8504-145c84d8b6f7", "name": "RULE-FNDUpcqPTaWnnHORtaiy", "state": "OK", "account": "user.RobertMiller", "subscription": { "name": "FUBEbEzxZpwpaQmXJutJ", "account": "user.ElizabethJacobs" }, "last_modified": new Date("Sun, 05 Feb 2023 07:16:35 UTC") },
            { "id": "8095ca8f-3544-4079-8911-990ace7496dd", "name": "RULE-rxCMGASmZwPNjzBJqocO", "state": "Suspended", "account": "user.MichaelMarks", "subscription": { "name": "qTFyCWkJborFyNTCRUNr", "account": "user.KathrynSchneider" }, "last_modified": new Date("Thu, 09 Feb 2023 01:27:20 UTC") },
            { "id": "63dcd0c2-3268-481d-ac1e-75adc6eb866b", "name": "RULE-tVOHwsIycIPxLhxIfypx", "state": "Waiting_Approval", "account": "user.LauraSchneider", "subscription": { "name": "svpvsPyEXjHsVCulAYPJ", "account": "user.AshleyLopez" }, "last_modified": new Date("Mon, 13 Feb 2023 01:31:55 UTC") },
            { "id": "59938aa8-c2d2-413d-8f46-8a2c4f945cd5", "name": "RULE-AgHSBHQkUwgpPxtmueAJ", "state": "Replicating", "account": "user.MatthewHobbs", "subscription": { "name": "SnZXNujkzHcHzDGGYKvO", "account": "user.TiffanyRobbins" }, "last_modified": new Date("Sat, 07 Jan 2023 07:20:41 UTC") },
            { "id": "f14705ae-13c1-4b37-9aae-a995cb0af285", "name": "RULE-RZfQDEKypJUUyRQBpzou", "state": "Suspended", "account": "user.MichaelHill", "subscription": { "name": "TbAAhJcTgIvAmxPltrNI", "account": "user.BobbyLutz" }, "last_modified": new Date("Tue, 18 Apr 2023 01:36:25 UTC") },
            { "id": "bdd08eee-db19-46b7-aa9b-3ff327dd0e47", "name": "RULE-BzoJBPFuAxzTKXKQoduw", "state": "Stuck", "account": "user.FranciscoJacobs", "subscription": { "name": "cDQcCNEkcHzwItNVeXlQ", "account": "user.AdamAllen" }, "last_modified": new Date("Sun, 29 Jan 2023 22:38:58 UTC") },
            { "id": "c2841e20-76eb-4fd3-b660-e67298d5af75", "name": "RULE-edspsxYFbnSbJaFwBQyv", "state": "Suspended", "account": "user.ToddNelson", "subscription": { "name": "cTHAxJDXgVutZYtpqmBt", "account": "user.JonRodriguez" }, "last_modified": new Date("Wed, 01 Feb 2023 17:48:45 UTC") },
            { "id": "b873f2e7-ea81-4f86-97e3-aa3de9b34028", "name": "RULE-dlJqKGTipHnpbgaqnBLZ", "state": "Waiting_Approval", "account": "user.CraigDoyle", "subscription": { "name": "FRwPNlOhKBvNoveeuauT", "account": "user.DavidMckenzie" }, "last_modified": new Date("Mon, 23 Jan 2023 22:41:39 UTC") },
            { "id": "19269e9d-d02d-4aec-9907-8a655c1b0504", "name": "RULE-JxsmyTahdRWseqDTnTtl", "state": "Replicating", "account": "user.KimberlyClarke", "subscription": { "name": "JbRlHlcWqMvTwWaMmJkr", "account": "user.DavidAnderson" }, "last_modified": new Date("Wed, 08 Feb 2023 22:32:46 UTC") },
            { "id": "3df788f0-b643-4e80-bbf2-ddd8d8cc8ee8", "name": "RULE-kMqOidTwVaQtPbZjveiK", "state": "Inject", "account": "user.BrandonThornton", "subscription": { "name": "fLseTFVdWWfWzeZtCFVO", "account": "user.AlyssaDean" }, "last_modified": new Date("Mon, 02 Jan 2023 15:52:53 UTC") },
            { "id": "a2bcb0d0-2587-4c32-80ac-b974f5a0147c", "name": "RULE-MhNhSfzCYVuPLaQbmnaT", "state": "Waiting_Approval", "account": "user.ToddAnthony", "subscription": { "name": "DbRkZurNJKmCiqMatCmW", "account": "user.AndrewNelson" }, "last_modified": new Date("Thu, 23 Feb 2023 19:20:53 UTC") },
            { "id": "3766520c-612b-4a9c-9f90-9e6bdc32f776", "name": "RULE-zlijGEgSKrTMhgIwnDQx", "state": "Inject", "account": "user.AmyDavila", "subscription": { "name": "bOnOuRmzpQfYoXOyXuId", "account": "user.BrandonJohnson" }, "last_modified": new Date("Mon, 09 Jan 2023 17:35:46 UTC") },
            { "id": "77f8950d-2830-41ee-a756-183bcc9cb866", "name": "RULE-nGLebBrQJugIGndtnbYb", "state": "Replicating", "account": "user.EricDuncan", "subscription": { "name": "TOuwtndbAieUdYjPwkiz", "account": "user.StaceyDodson" }, "last_modified": new Date("Fri, 05 May 2023 12:03:24 UTC") },
            { "id": "2e20433b-2736-4fa5-8cba-705cec0a7e42", "name": "RULE-ooyivEmeVLQzYsEPZWMs", "state": "OK", "account": "user.JaniceValdez", "subscription": { "name": "wPhUemRjbrtaxMKRYfcR", "account": "user.KimHernandez" }, "last_modified": new Date("Mon, 02 Jan 2023 04:07:58 UTC") },
            { "id": "f9d6e2db-a939-43bd-ab62-f4c95031c834", "name": "RULE-ESXlQrCeTZDnPHYaKVVL", "state": "Replicating", "account": "user.RonaldHolloway", "subscription": { "name": "PLYpzOvTwLklSFCqgKAe", "account": "user.MatthewMcintyre" }, "last_modified": new Date("Thu, 19 Jan 2023 16:25:25 UTC") },
            { "id": "9ea6c52e-4b18-494c-8c2b-d308a19e0dc3", "name": "RULE-GJYwhkyjDCDSAmgkPezB", "state": "Waiting_Approval", "account": "user.JustinThomas", "subscription": { "name": "pgMTIBetXNsqBuRKEmhK", "account": "user.AlexanderGonzalez" }, "last_modified": new Date("Sun, 12 Mar 2023 17:21:16 UTC") },
            { "id": "28c4d2ed-7476-4912-9adb-51a4eb33fa6e", "name": "RULE-VhZNrOTFbZJZKXzFmdyP", "state": "Inject", "account": "user.KimberlyHamilton", "subscription": { "name": "glDSRHzzzfDQOHAdJAhZ", "account": "user.KellyWard" }, "last_modified": new Date("Fri, 10 Mar 2023 22:47:19 UTC") },
            { "id": "9aa3f0c0-cb30-4c4c-a8a7-3c7e2ae8ced5", "name": "RULE-VYBTRpBQxivpsoWoTYGO", "state": "Stuck", "account": "user.JoshuaRamirez", "subscription": { "name": "DJwMgWXgVKmEAHoIBUHm", "account": "user.LoriWashington" }, "last_modified": new Date("Tue, 24 Jan 2023 18:35:58 UTC") },
            { "id": "d418065a-6ffb-4058-9cbf-e76c61c16a57", "name": "RULE-IpordFnRjlaGCpGBpOAH", "state": "Stuck", "account": "user.TylerRodriguez", "subscription": { "name": "lPRcXnJKRQUfHHYYZraI", "account": "user.TheresaGriffin" }, "last_modified": new Date("Wed, 01 Feb 2023 03:14:40 UTC") },
            { "id": "4d14ce93-9838-4cbc-a927-7ccdd390b27b", "name": "RULE-zSqOGbQEWkCvGEnekbiP", "state": "Stuck", "account": "user.SabrinaCruz", "subscription": { "name": "NDjxkPGtMkuXORoOuhoO", "account": "user.PatriciaCoffey" }, "last_modified": new Date("Wed, 29 Mar 2023 18:08:05 UTC") },
            { "id": "c59b4e44-5828-47bd-babf-604005d0849d", "name": "RULE-FztVxbWdiGlLiURRvspU", "state": "Replicating", "account": "user.VanessaRamos", "subscription": { "name": "YjrBpFvfOSiLsoPrpQPg", "account": "user.KatherineSmith" }, "last_modified": new Date("Mon, 23 Jan 2023 20:38:48 UTC") },
            { "id": "6eda2151-5b95-4d68-9ba1-cbdd9d7e7fae", "name": "RULE-jCGAoBAisoqYaiCshQzX", "state": "OK", "account": "user.AllenHenderson", "subscription": { "name": "THNhttSAxWfSComXcXBN", "account": "user.AustinStephenson" }, "last_modified": new Date("Wed, 03 May 2023 04:13:48 UTC") },
            { "id": "056a0666-1606-4393-affb-537458ce5b6f", "name": "RULE-GwOGIMvHbNVCBwAstiiZ", "state": "Inject", "account": "user.AnnClarke", "subscription": { "name": "CZTfadrzhPLiAOoPnTkc", "account": "user.JonathanShaw" }, "last_modified": new Date("Wed, 10 May 2023 07:14:52 UTC") },
            { "id": "5a4820bf-25e7-4e77-9bf4-d07a4199d1a4", "name": "RULE-eODTdduuRdRkbAScLbbX", "state": "Stuck", "account": "user.JessicaPeck", "subscription": { "name": "KSfYZapXrOOaOWUiLuxE", "account": "user.CoreyMiller" }, "last_modified": new Date("Wed, 10 May 2023 22:59:29 UTC") },
            { "id": "3ffb4d6e-b3c6-4c6f-9526-d83c5460ed20", "name": "RULE-NTrJSXBgobHrhSPPmBGN", "state": "Replicating", "account": "user.GinaPena", "subscription": { "name": "wtWFgGTptQSwMcjoPTEg", "account": "user.JamesWest" }, "last_modified": new Date("Fri, 13 Jan 2023 20:35:55 UTC") },
            { "id": "796acbe5-8cff-4874-a3cc-6a3c9c629414", "name": "RULE-CBSEbKwqyctNpUkPLfNL", "state": "Stuck", "account": "user.EmmaCarson", "subscription": { "name": "yLvyJXjKflPfjjwqamOz", "account": "user.KimberlyRiley" }, "last_modified": new Date("Fri, 31 Mar 2023 17:55:38 UTC") },
            { "id": "33656a53-fe7f-4faa-a381-b42648c1718e", "name": "RULE-rQOtJdzFirENXcDKxbuW", "state": "Suspended", "account": "user.CarolFinley", "subscription": { "name": "EQmdBZfCgojJNKghWVMP", "account": "user.DawnRoss" }, "last_modified": new Date("Sun, 09 Apr 2023 01:27:19 UTC") },
            { "id": "a456bd51-e57c-4b7c-9f16-9512aaa7c6d4", "name": "RULE-DtuLJLoIWnMerpGJktdu", "state": "Inject", "account": "user.NatalieWilkerson", "subscription": { "name": "NlmSyQPuRffnMdJCIaMW", "account": "user.SusanJohnson" }, "last_modified": new Date("Mon, 10 Apr 2023 15:07:09 UTC") },
            { "id": "eaa0806c-79af-4fbf-beeb-d75bcb3d4b60", "name": "RULE-RqYWmDzLaQaSSgNIRAWE", "state": "Replicating", "account": "user.EmilyFlores", "subscription": { "name": "BjvgnDIGrnPkssIKoHEN", "account": "user.ChristopherHardy" }, "last_modified": new Date("Wed, 26 Apr 2023 13:16:12 UTC") },
            { "id": "033b029d-8dd0-4499-90c1-e57cb95e6901", "name": "RULE-CXnklnzVzuwiEbNywmth", "state": "OK", "account": "user.StevenStephens", "subscription": { "name": "MVCtgQMHpsBAKLuJbCjS", "account": "user.CodyThomas" }, "last_modified": new Date("Sun, 12 Feb 2023 12:02:46 UTC") },
            { "id": "9e12586e-9366-4552-bb3d-1839252032ea", "name": "RULE-sbdwjsGrLEHceugItKkf", "state": "Replicating", "account": "user.LarryCooper", "subscription": { "name": "nhCaaCezirEMFZSKEzjw", "account": "user.JoshuaJohnson" }, "last_modified": new Date("Sat, 08 Apr 2023 20:09:48 UTC") },
            { "id": "d1eac723-5250-4d19-923e-b01c240522ab", "name": "RULE-GcznxpPQZtMViilIpXhb", "state": "Inject", "account": "user.WilliamSmith", "subscription": { "name": "kXcfjlnhXDDJogIyNwEA", "account": "user.DeborahRyan" }, "last_modified": new Date("Fri, 07 Apr 2023 03:35:57 UTC") },
            { "id": "4f44fc4c-7d21-4f07-a6cb-1a7d17c2b08f", "name": "RULE-IkebfblXUsWWYPenimuC", "state": "OK", "account": "user.ChristinaCantu", "subscription": { "name": "vGLoWSRhfbHwxQhCvNma", "account": "user.EricFoster" }, "last_modified": new Date("Mon, 20 Mar 2023 07:59:57 UTC") },
            { "id": "51d7d7a8-eb8b-4a76-8155-d4b0eae53845", "name": "RULE-yhirQTtwOZhRxpbvCgee", "state": "Waiting_Approval", "account": "user.ElizabethSpence", "subscription": { "name": "ymtpMCbFBVuTBLlDfYyd", "account": "user.SeanGates" }, "last_modified": new Date("Sat, 29 Apr 2023 05:26:58 UTC") },
            { "id": "adc979bc-9d1e-4926-aaa4-222dd84973cc", "name": "RULE-uEtTwfFJYbGRMogSGqvn", "state": "Waiting_Approval", "account": "user.NatashaVaughn", "subscription": { "name": "RzehHwbgrwHccoKSTiCH", "account": "user.TammyCrawford" }, "last_modified": new Date("Thu, 13 Apr 2023 16:09:39 UTC") },
            { "id": "feb73392-2ffb-4588-bb56-db21f0397ffb", "name": "RULE-MUzofnINCBlbCRWDbqPJ", "state": "Replicating", "account": "user.AlexAli", "subscription": { "name": "noBXjbyjdlABOrcKKIIh", "account": "user.JenniferCarroll" }, "last_modified": new Date("Tue, 24 Jan 2023 17:29:32 UTC") },
            { "id": "6b9c2fcc-9cf6-4a3d-988e-0b64b44e1cb3", "name": "RULE-jTmhopHyGtFQSchXPMZS", "state": "OK", "account": "user.TommySmith", "subscription": { "name": "hXJdzYfVmbIcFeDQcYUV", "account": "user.EricHughes" }, "last_modified": new Date("Tue, 18 Apr 2023 19:04:50 UTC") },
            { "id": "c8307d59-3d8b-4523-bce8-eb75e928191f", "name": "RULE-OSeZLkFvJGhrqMmRaxdR", "state": "Inject", "account": "user.KeithLawrence", "subscription": { "name": "kGgAFBZFYgymrKigQsyW", "account": "user.RebeccaGilbert" }, "last_modified": new Date("Sun, 05 Mar 2023 13:41:41 UTC") },
            { "id": "77c949c9-d295-45a3-91a1-fff484080d46", "name": "RULE-LGKKKTHNXHDZJLzUFRpJ", "state": "Replicating", "account": "user.ChristopherBrewer", "subscription": { "name": "uNbpZhWNBnYbNzquMeAV", "account": "user.HectorClark" }, "last_modified": new Date("Fri, 03 Feb 2023 10:25:11 UTC") },

        ],
        fetchStatus: "idle"
    },
    // Contents
    didContentsSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didContentsResponse: {
        data: [
            { "scope": "user.JonathanPerry", "name": "container-CiFhxTRuwjdvaQQeELSz", "did_type": "Container" },
            { "scope": "user.KristenRoberts", "name": "container-FBhdaoLCaXWGhkITdZDo", "did_type": "Container" },
            { "scope": "user.LindsayCunningham", "name": "container-sjtligDkHFzCvTlHHViB", "did_type": "Container" },
            { "scope": "user.MichelleNelson", "name": "container-ywVaczrfQxnWBKlSWdHS", "did_type": "Dataset" },
            { "scope": "user.ElizabethWong", "name": "dataset-NOKpAdZHtZJGWXUJZgLL", "did_type": "Container" },
            { "scope": "user.JasonThompson", "name": "dataset-HvjKaFsxdEfFgtPwJsVN", "did_type": "Container" },
            { "scope": "user.RobertLewis", "name": "container-ArwcGlrcDYGmQQrUFjvX", "did_type": "Container" },
            { "scope": "user.TammyWilson", "name": "dataset-VYTPOCwsECetZENrtvET", "did_type": "Container" },
            { "scope": "user.EmilyPatterson", "name": "container-DuEUODGkTvhhWsoLOZGz", "did_type": "Dataset" },
            { "scope": "user.BethMontes", "name": "dataset-fFFmkKdGzwrCnZxcgfva", "did_type": "Container" },
            { "scope": "user.MicheleLee", "name": "container-yDaHisaijzWyJPDCmYKn", "did_type": "Dataset" },
            { "scope": "user.RyanJenkins", "name": "container-CdWbKaqikyBXDsVhuFps", "did_type": "Dataset" },
            { "scope": "user.StephanieRice", "name": "container-lNDVuIPsuUMZuTonUszn", "did_type": "Dataset" },
            { "scope": "user.DennisMejia", "name": "dataset-kYUROcXgfgMlqqhPTzUL", "did_type": "Container" },
            { "scope": "user.RachelMunoz", "name": "dataset-FhBstRFhkQpothGBrmvZ", "did_type": "Dataset" },
            { "scope": "user.ZacharyPeterson", "name": "container-LllblDRkBkhikKgvibLy", "did_type": "Container" },
            { "scope": "user.NicholasMoore", "name": "container-OBWskIpfjLsXcuwUljeA", "did_type": "Container" },
            { "scope": "user.NathanMartin", "name": "container-xjeeufdwZfyXZFTNLnwK", "did_type": "Dataset" },
            { "scope": "user.ValerieBrown", "name": "dataset-zmNgBZUyeBPgnzgsyXuA", "did_type": "Dataset" },
            { "scope": "user.DennisPrice", "name": "dataset-SzdvUGoaSwwRIPpYRoNi", "did_type": "Dataset" },
            { "scope": "user.BonnieKing", "name": "dataset-DCdMCvRVEKBRfDnyGNmM", "did_type": "Container" },
            { "scope": "user.JustinKirby", "name": "dataset-muYJhMUhfbXbOORnPsho", "did_type": "Container" },
            { "scope": "user.PamelaRobbins", "name": "container-bAoZCwskmlyRFInaMxYt", "did_type": "Dataset" },
            { "scope": "user.CatherineSpencer", "name": "container-TAUKSbZyGLNKVrLJlVIW", "did_type": "Container" },
            { "scope": "user.SophiaHarris", "name": "dataset-cozvFMvuuHyFVnAKHboi", "did_type": "Dataset" },
            { "scope": "user.LisaAllen", "name": "dataset-HcndjXlpgWKFeMbBeDql", "did_type": "Container" },
            { "scope": "user.ChristopherFlowers", "name": "dataset-ZQiLbIEGqJCFArddilDf", "did_type": "Container" },
            { "scope": "user.KarenRusso", "name": "container-wnWKmRiByhbGlhKwZUiy", "did_type": "Dataset" },
            { "scope": "user.BrittneyMejia", "name": "dataset-oBqmQaHdqpjkJtKaWOJE", "did_type": "Dataset" },
            { "scope": "user.SuzanneSmith", "name": "dataset-UYHhwaQlAVXrjOSYjLyl", "did_type": "Container" },
            { "scope": "user.LisaRowland", "name": "dataset-KxvstUMDvvomIxCwpxky", "did_type": "Container" },
            { "scope": "user.AlexaMiller", "name": "dataset-TCcJGwSdbIJhHGjyuRAb", "did_type": "Container" },
            { "scope": "user.JohnWebb", "name": "container-zDHjDueoVabztvUdXCso", "did_type": "Container" },
            { "scope": "user.PeterBauer", "name": "dataset-hGlqlAFEFKJpUmKrZsUa", "did_type": "Container" },
            { "scope": "user.JavierRiley", "name": "dataset-RMBaYybySwUuDsUhoUpP", "did_type": "Dataset" },
            { "scope": "user.TinaSanchez", "name": "dataset-CuSbZNIWBaUJiFiZyIXJ", "did_type": "Container" },
            { "scope": "user.JohnHo", "name": "container-xesLHpwYmGLGyYLShNjB", "did_type": "Dataset" },
            { "scope": "user.DorothyVelez", "name": "dataset-XLyjjWEJZxYmBqGrEuEq", "did_type": "Dataset" },
            { "scope": "user.NatalieDickerson", "name": "container-FhoPFizJEUKTAvsZHKlZ", "did_type": "Dataset" },
            { "scope": "user.TommyReynolds", "name": "dataset-uUVenbBvzqMqgLjHNqiV", "did_type": "Container" },
            { "scope": "user.MonicaSanchez", "name": "container-tKaYFFofdbTRZlLLHJEp", "did_type": "Dataset" },
            { "scope": "user.MatthewCrawford", "name": "container-gJFkhjPsqYXcnEBHraNz", "did_type": "Dataset" },
            { "scope": "user.TroyGreer", "name": "container-dOmcBYhyvtXWmAOZaFVO", "did_type": "Container" },
            { "scope": "user.SaraWong", "name": "dataset-VTLgsxDkyeQwxXnBbwPn", "did_type": "Container" },
            { "scope": "user.NicholeChandler", "name": "container-kinqxtQnYYSuMBqiCBcl", "did_type": "Container" },
            { "scope": "user.CynthiaLewis", "name": "dataset-kxwpLEdrJsLYkrZvbxZd", "did_type": "Container" },
            { "scope": "user.JamesPratt", "name": "container-uhQVhcEDCbBogmOljKke", "did_type": "Container" },
            { "scope": "user.NicholasChase", "name": "container-VBocIpNtSkuvvbNpxhsI", "did_type": "Container" },
            { "scope": "user.MichaelBlack", "name": "container-HVzdplMhIJoKoLyeEVpT", "did_type": "Container" },
            { "scope": "user.BeverlyMitchell", "name": "dataset-FcTphEovdbHHAgkqzckp", "did_type": "Dataset" },
            { "scope": "user.RobertHogan", "name": "container-KmlbKNNBAsbnIIgiGhck", "did_type": "Container" },
            { "scope": "user.DonnaCaldwell", "name": "dataset-sLZLSijmRkKdPQQtIkTd", "did_type": "Dataset" },
            { "scope": "user.LisaLarson", "name": "dataset-UYBfijCmuTqOsEosnZiW", "did_type": "Container" },
            { "scope": "user.DanielLozano", "name": "container-YtszvcuFJkYBsPjrtEKC", "did_type": "Container" },
            { "scope": "user.JustinYang", "name": "container-VHLnVpXHKhhLCscsdLCz", "did_type": "Container" },
            { "scope": "user.ChristopherConner", "name": "container-mkxfgftGGotTbGzYidlA", "did_type": "Container" },
            { "scope": "user.RandyHoward", "name": "dataset-FUClHSeGYPraCwdkdURO", "did_type": "Container" },
            { "scope": "user.TylerRobbins", "name": "container-egZXJFbEPlhZtDESXGKP", "did_type": "Dataset" },
            { "scope": "user.RichardBaker", "name": "container-HeRnYBmVFMuoqQiQoNTg", "did_type": "Container" },
            { "scope": "user.ParkerThomas", "name": "container-SxMhJdjPpowdYnlzPJJp", "did_type": "Container" },
            { "scope": "user.StephenMcknight", "name": "container-OWwKVnMpCeWFnCamTsck", "did_type": "Container" },
            { "scope": "user.MargaretRogers", "name": "dataset-PRDcEfPsqMWBDemsbZBV", "did_type": "Container" },
            { "scope": "user.StephanieMoore", "name": "dataset-wWdqanoWyWZFmtMXONkP", "did_type": "Container" },
            { "scope": "user.AdamSolis", "name": "dataset-ZKVtNoUwhRkvBOyrkDTN", "did_type": "Container" },
            { "scope": "user.LauraClark", "name": "dataset-APEiEbweQvWuAqcZBjYX", "did_type": "Container" },
            { "scope": "user.BrandiTaylor", "name": "dataset-YoGzQvDRmjkpqhpmRNBP", "did_type": "Container" },
            { "scope": "user.KathleenLin", "name": "container-aMOZOKQoPMXbRxnIFVvq", "did_type": "Dataset" },
            { "scope": "user.GregoryBurke", "name": "container-PmrbbYgwpkLtMhKCCXTe", "did_type": "Dataset" },
            { "scope": "user.RebeccaCarter", "name": "container-RMBHQzIAcYdiDqnzjLFC", "did_type": "Dataset" },
            { "scope": "user.EvanSchneider", "name": "container-xTtElpBaggiYUfrxzDkV", "did_type": "Container" },
            { "scope": "user.JeremyPatel", "name": "dataset-HNBXPedhYFaBfittJTcQ", "did_type": "Dataset" },
            { "scope": "user.TamaraPowell", "name": "container-XziLmJOqZUtAETjfGZOa", "did_type": "Dataset" },
            { "scope": "user.LonnieJones", "name": "dataset-RGzmNpwPdqArCHIYFPUw", "did_type": "Container" },
            { "scope": "user.JulieBennett", "name": "dataset-ZUlRNGBUJmsauKBWcHas", "did_type": "Container" },
            { "scope": "user.MichaelBryant", "name": "dataset-qtfuGBAXgvHDKktNTDex", "did_type": "Container" },
            { "scope": "user.MelindaWade", "name": "dataset-uBGkqMDikoKGlmyneyyu", "did_type": "Container" },
            { "scope": "user.LoriLewis", "name": "container-jFerYByeDfHsEEzyBMDJ", "did_type": "Container" },
            { "scope": "user.HeatherBell", "name": "dataset-ZvtQGiAlSFJZNqlKczYm", "did_type": "Dataset" },
            { "scope": "user.RebeccaRowland", "name": "dataset-jiKtRyCkYIURaYkPtaXT", "did_type": "Dataset" },
            { "scope": "user.BrendaAlexander", "name": "container-UHDeQjWwxpOSrvaGOOKm", "did_type": "Container" },
            { "scope": "user.WilliamByrd", "name": "container-usIyRQICDvtJvSPbxgfe", "did_type": "Container" },
            { "scope": "user.BruceHolloway", "name": "dataset-oSwhbUWHPOmXVdaxTsbQ", "did_type": "Container" },
            { "scope": "user.SamanthaThompson", "name": "dataset-KwGGRweNamLbZjXRBhXc", "did_type": "Dataset" },
            { "scope": "user.MarieWilliams", "name": "container-OhpheVMIMCBENPLEAJxO", "did_type": "Container" },
            { "scope": "user.ReginaldLopez", "name": "container-jNOIrXMOWjcufRGmsKih", "did_type": "Container" },
            { "scope": "user.TylerCervantes", "name": "container-ePtRRjtOYgnuzEFjcXKO", "did_type": "Container" },
            { "scope": "user.YvonneBurch", "name": "container-utWSEwtYIFSRqehKsCta", "did_type": "Dataset" },
            { "scope": "user.StevenEvans", "name": "dataset-XyclDKIZIWEObsetPnUh", "did_type": "Dataset" },
            { "scope": "user.MelindaHunter", "name": "container-ObLvyUuZBBbZHmBGSNkr", "did_type": "Container" },
            { "scope": "user.KatrinaJohnson", "name": "container-CycXtGUWyBKZBoSFHkzi", "did_type": "Dataset" },
            { "scope": "user.TimothyHansen", "name": "dataset-AtEEUPYGaYRBMSdqcMKv", "did_type": "Container" },
            { "scope": "user.JanetHoffman", "name": "container-mCMgkEhBLUpduwjPSVHM", "did_type": "Dataset" },
            { "scope": "user.LuisWright", "name": "dataset-mLETNnlzHWJNhWOoVWgX", "did_type": "Container" },
            { "scope": "user.RobertSmith", "name": "container-QvMVjxggobzWZcxEBEDi", "did_type": "Dataset" },
            { "scope": "user.KevinMiller", "name": "container-MLSUueVCEfcjrfkYWpmy", "did_type": "Container" },
            { "scope": "user.BrendaRich", "name": "dataset-aKzqhsRscYRbHQpRekXp", "did_type": "Container" },
            { "scope": "user.BethanyJames", "name": "container-tMoCTdkePVTrIAjKQXLe", "did_type": "Dataset" },
            { "scope": "user.WilliamAnderson", "name": "dataset-WVGuXufUnjUPlJZSzuTz", "did_type": "Container" },
            { "scope": "user.JenniferWise", "name": "dataset-DEVVgemaOOuhMqBawUvL", "did_type": "Dataset" },
            { "scope": "user.ThomasSmall", "name": "container-YaQGxbdHDdaPRHiMTSgg", "did_type": "Container" }
        ],
        fetchStatus: "idle",
    },
    didDatasetReplicasSearch: (didSearchQuery: DIDSearchQuery) => { console.log(didSearchQuery) },
    didDatasetReplicasResponse: {
        data: [
            { "rse": "RSE-JvNHGIciYVONHnlcPytz", "rseblocked": 0, "availability": true, "available_files": 82, "available_bytes": 673000000000, "creation_date": new Date(2014, 11, 2), "last_accessed": new Date("Thu, 04 May 2023 09:41:04 UTC") },
            { "rse": "RSE-NswnryZNkhhwTWBJnxqp", "rseblocked": 0, "availability": false, "available_files": 49, "available_bytes": 181000, "creation_date": new Date(2020, 11, 20), "last_accessed": new Date("Sun, 01 Jan 2023 03:36:42 UTC") },
            { "rse": "RSE-zJjGTyNbgmktBroIgHeb", "rseblocked": 0, "availability": false, "available_files": 83, "available_bytes": 344000, "creation_date": new Date(2019, 1, 22), "last_accessed": new Date("Tue, 07 Feb 2023 17:48:02 UTC") },
            { "rse": "RSE-BiPpqkDEduquMfVMGjFW", "rseblocked": 7, "availability": false, "available_files": 0, "available_bytes": 503000, "creation_date": new Date(2015, 3, 16), "last_accessed": new Date("Mon, 03 Apr 2023 09:12:14 UTC") },
            { "rse": "RSE-iZrYuNKtneTgZXyZyaoz", "rseblocked": 3, "availability": false, "available_files": 54, "available_bytes": 902000000000, "creation_date": new Date(2019, 3, 28), "last_accessed": new Date("Fri, 05 May 2023 08:37:34 UTC") },
            { "rse": "RSE-NJqePcgAKpoNXUTCueVQ", "rseblocked": 2, "availability": false, "available_files": 22, "available_bytes": 439000000000, "creation_date": new Date(2017, 9, 15), "last_accessed": new Date("Tue, 25 Apr 2023 23:02:11 UTC") },
            { "rse": "RSE-rPPxHRfNgRoSHUWYkErn", "rseblocked": 0, "availability": true, "available_files": 71, "available_bytes": 291000, "creation_date": new Date(2016, 10, 26), "last_accessed": new Date("Wed, 26 Apr 2023 06:45:58 UTC") },
            { "rse": "RSE-yiCjLRBqJlfGKlBtkmFn", "rseblocked": 0, "availability": false, "available_files": 60, "available_bytes": 1000000, "creation_date": new Date(2019, 5, 7), "last_accessed": new Date("Mon, 13 Mar 2023 12:21:15 UTC") },
            { "rse": "RSE-BQpCtYJNVaHswNPfgsiz", "rseblocked": 2, "availability": true, "available_files": 91, "available_bytes": 537000000, "creation_date": new Date(2021, 2, 5), "last_accessed": new Date("Tue, 14 Feb 2023 08:24:53 UTC") },
            { "rse": "RSE-vPiLvHaQcBLINGApclDv", "rseblocked": 0, "availability": false, "available_files": 36, "available_bytes": 853000, "creation_date": new Date(2016, 1, 26), "last_accessed": new Date("Thu, 19 Jan 2023 09:00:20 UTC") },
            { "rse": "RSE-ZRLCtNCLHehAwokuogOf", "rseblocked": 2, "availability": false, "available_files": 55, "available_bytes": 76000000, "creation_date": new Date(2015, 9, 12), "last_accessed": new Date("Tue, 18 Apr 2023 23:05:10 UTC") },
            { "rse": "RSE-RoHrDNpKpyJtecITGvwF", "rseblocked": 0, "availability": true, "available_files": 20, "available_bytes": 622000000000, "creation_date": new Date(2020, 8, 6), "last_accessed": new Date("Tue, 31 Jan 2023 01:03:48 UTC") },
            { "rse": "RSE-BjMXAQcPRBbfFWfssIbe", "rseblocked": 0, "availability": false, "available_files": 40, "available_bytes": 434000, "creation_date": new Date(2017, 8, 31), "last_accessed": new Date("Sun, 12 Mar 2023 06:39:29 UTC") },
            { "rse": "RSE-fyPbHPJkzbTmBqBPokAO", "rseblocked": 3, "availability": true, "available_files": 40, "available_bytes": 89, "creation_date": new Date(2016, 6, 17), "last_accessed": new Date("Sun, 23 Apr 2023 21:20:43 UTC") },
            { "rse": "RSE-krlUdRMIfxeqJfAbcBve", "rseblocked": 0, "availability": true, "available_files": 59, "available_bytes": 709000, "creation_date": new Date(2020, 2, 15), "last_accessed": new Date("Wed, 15 Feb 2023 10:48:18 UTC") },
            { "rse": "RSE-AvIORfDSHHTwyNZsfvpU", "rseblocked": 0, "availability": true, "available_files": 80, "available_bytes": 923000000000, "creation_date": new Date(2018, 10, 1), "last_accessed": new Date("Wed, 22 Mar 2023 18:36:18 UTC") },
            { "rse": "RSE-jdJPGXCyAuGTHInxixZv", "rseblocked": 5, "availability": false, "available_files": 56, "available_bytes": 747000000000, "creation_date": new Date(2015, 2, 18), "last_accessed": new Date("Sat, 11 Feb 2023 23:37:25 UTC") },
            { "rse": "RSE-tfkdfFNDlblDPSLpHzqv", "rseblocked": 0, "availability": true, "available_files": 64, "available_bytes": 127000, "creation_date": new Date(2017, 9, 19), "last_accessed": new Date("Mon, 10 Apr 2023 13:34:55 UTC") },
            { "rse": "RSE-sjPKXaPzzMgGvrKhuhtW", "rseblocked": 0, "availability": true, "available_files": 80, "available_bytes": 260000000000, "creation_date": new Date(2019, 12, 15), "last_accessed": new Date("Fri, 24 Feb 2023 18:38:28 UTC") },
            { "rse": "RSE-sCIASjOmYdImunJRwJtw", "rseblocked": 0, "availability": false, "available_files": 71, "available_bytes": 629000, "creation_date": new Date(2018, 8, 13), "last_accessed": new Date("Sat, 04 Feb 2023 22:46:28 UTC") },
            { "rse": "RSE-JpLVfpfDLhkKnMVxbSQm", "rseblocked": 0, "availability": false, "available_files": 79, "available_bytes": 124000, "creation_date": new Date(2016, 3, 19), "last_accessed": new Date("Sat, 08 Apr 2023 15:46:53 UTC") },
            { "rse": "RSE-HTKpsChbbsYVCtscIYKu", "rseblocked": 0, "availability": false, "available_files": 65, "available_bytes": 369, "creation_date": new Date(2020, 4, 7), "last_accessed": new Date("Fri, 06 Jan 2023 16:08:48 UTC") },
            { "rse": "RSE-HTlWTwBqweZacrtTNPXt", "rseblocked": 0, "availability": false, "available_files": 99, "available_bytes": 422, "creation_date": new Date(2015, 3, 7), "last_accessed": new Date("Wed, 10 May 2023 17:22:41 UTC") },
            { "rse": "RSE-GrHxwKkbrgbjIVstgtNS", "rseblocked": 0, "availability": true, "available_files": 51, "available_bytes": 246000000, "creation_date": new Date(2019, 8, 9), "last_accessed": new Date("Mon, 06 Mar 2023 15:20:34 UTC") },
            { "rse": "RSE-XJnAVeweipXPOYvXwHTF", "rseblocked": 7, "availability": true, "available_files": 4, "available_bytes": 709000, "creation_date": new Date(2018, 10, 25), "last_accessed": new Date("Wed, 08 Feb 2023 03:20:23 UTC") },
            { "rse": "RSE-vnSvZiSZNzPnCSmoYRNW", "rseblocked": 0, "availability": false, "available_files": 57, "available_bytes": 520, "creation_date": new Date(2017, 2, 11), "last_accessed": new Date("Thu, 13 Apr 2023 13:15:12 UTC") },
            { "rse": "RSE-ZvShtlHVzWQxVFcUJwyg", "rseblocked": 0, "availability": false, "available_files": 71, "available_bytes": 525000000, "creation_date": new Date(2019, 2, 2), "last_accessed": new Date("Fri, 28 Apr 2023 16:40:34 UTC") },
            { "rse": "RSE-wnVETzevOMeKqzrwlbTO", "rseblocked": 0, "availability": true, "available_files": 12, "available_bytes": 715000, "creation_date": new Date(2018, 5, 25), "last_accessed": new Date("Sun, 01 Jan 2023 02:50:04 UTC") },
            { "rse": "RSE-nykDlzhPtZNUkYFTGgkb", "rseblocked": 0, "availability": false, "available_files": 3, "available_bytes": 830000000000, "creation_date": new Date(2016, 7, 3), "last_accessed": new Date("Mon, 10 Apr 2023 14:52:57 UTC") },
            { "rse": "RSE-LxTUQUskIcnqrwxoYSla", "rseblocked": 0, "availability": true, "available_files": 32, "available_bytes": 436000000000, "creation_date": new Date(2014, 7, 14), "last_accessed": new Date("Fri, 06 Jan 2023 07:24:25 UTC") },
            { "rse": "RSE-ZAtlVNeFXxLFdkYdjmya", "rseblocked": 0, "availability": true, "available_files": 78, "available_bytes": 116, "creation_date": new Date(2016, 5, 24), "last_accessed": new Date("Wed, 19 Apr 2023 00:36:47 UTC") },
            { "rse": "RSE-ySGcWCjQjNLsBTAphAFW", "rseblocked": 0, "availability": false, "available_files": 69, "available_bytes": 22000, "creation_date": new Date(2021, 3, 27), "last_accessed": new Date("Fri, 07 Apr 2023 01:58:06 UTC") },
            { "rse": "RSE-NTePivECVSuAIuHPCjpe", "rseblocked": 0, "availability": true, "available_files": 34, "available_bytes": 989000000, "creation_date": new Date(2019, 5, 16), "last_accessed": new Date("Sat, 21 Jan 2023 16:19:43 UTC") },
            { "rse": "RSE-JiYzEuCtseTNjJsKuNEb", "rseblocked": 0, "availability": true, "available_files": 9, "available_bytes": 649, "creation_date": new Date(2018, 5, 8), "last_accessed": new Date("Fri, 05 May 2023 17:43:10 UTC") },
            { "rse": "RSE-zStUWAXdCjJMiIJXgVEy", "rseblocked": 0, "availability": true, "available_files": 68, "available_bytes": 31, "creation_date": new Date(2016, 4, 29), "last_accessed": new Date("Sat, 28 Jan 2023 19:10:26 UTC") },
            { "rse": "RSE-dWZFWRukkdHtMzsArbUJ", "rseblocked": 0, "availability": true, "available_files": 7, "available_bytes": 836000000, "creation_date": new Date(2019, 3, 13), "last_accessed": new Date("Thu, 19 Jan 2023 18:18:33 UTC") },
            { "rse": "RSE-UQrMWTEodGDMhMsDnihL", "rseblocked": 0, "availability": false, "available_files": 52, "available_bytes": 487, "creation_date": new Date(2021, 5, 10), "last_accessed": new Date("Fri, 07 Apr 2023 09:03:58 UTC") },
            { "rse": "RSE-UVFOiAtUdaoMZBRFpsuT", "rseblocked": 0, "availability": false, "available_files": 100, "available_bytes": 652000000000, "creation_date": new Date(2016, 3, 11), "last_accessed": new Date("Wed, 29 Mar 2023 01:25:40 UTC") },
            { "rse": "RSE-fryikmIopeblGGNNJmkW", "rseblocked": 2, "availability": false, "available_files": 59, "available_bytes": 889000000, "creation_date": new Date(2016, 12, 29), "last_accessed": new Date("Sat, 04 Mar 2023 01:23:28 UTC") },
            { "rse": "RSE-XsLEXIPHQHIrQPSToHyj", "rseblocked": 0, "availability": false, "available_files": 45, "available_bytes": 694000000, "creation_date": new Date(2016, 6, 15), "last_accessed": new Date("Tue, 04 Apr 2023 14:30:25 UTC") },
            { "rse": "RSE-dxpyKtUqpotOaHRjcAuJ", "rseblocked": 0, "availability": true, "available_files": 49, "available_bytes": 562, "creation_date": new Date(2015, 8, 20), "last_accessed": new Date("Thu, 27 Apr 2023 22:16:42 UTC") },
            { "rse": "RSE-mjbrJRCQmhRDbplKfkoD", "rseblocked": 0, "availability": false, "available_files": 30, "available_bytes": 692000000000, "creation_date": new Date(2020, 4, 2), "last_accessed": new Date("Sat, 04 Mar 2023 22:48:09 UTC") },
            { "rse": "RSE-YkwLzTLtMLaJnDTjEtVX", "rseblocked": 0, "availability": false, "available_files": 39, "available_bytes": 40000000000, "creation_date": new Date(2016, 11, 26), "last_accessed": new Date("Tue, 07 Feb 2023 12:54:42 UTC") },
            { "rse": "RSE-ikNmohArYQQdGoqatdnA", "rseblocked": 0, "availability": true, "available_files": 28, "available_bytes": 533000000, "creation_date": new Date(2018, 3, 14), "last_accessed": new Date("Mon, 23 Jan 2023 04:22:02 UTC") },
            { "rse": "RSE-lRgzcxdvkIpMgQtfHIBX", "rseblocked": 0, "availability": false, "available_files": 5, "available_bytes": 328000000, "creation_date": new Date(2018, 7, 26), "last_accessed": new Date("Sat, 11 Mar 2023 09:50:34 UTC") },
            { "rse": "RSE-HcXNBPsfCYKBPwfMVwLe", "rseblocked": 0, "availability": false, "available_files": 58, "available_bytes": 725000, "creation_date": new Date(2019, 9, 4), "last_accessed": new Date("Sat, 29 Apr 2023 18:12:13 UTC") },
            { "rse": "RSE-KDNlTfDNTGuILANeVRbv", "rseblocked": 0, "availability": false, "available_files": 44, "available_bytes": 25, "creation_date": new Date(2020, 7, 30), "last_accessed": new Date("Wed, 15 Mar 2023 15:13:47 UTC") },
            { "rse": "RSE-FzDuIlYfMmkPYYCTEjle", "rseblocked": 0, "availability": false, "available_files": 60, "available_bytes": 272000000, "creation_date": new Date(2017, 5, 30), "last_accessed": new Date("Wed, 11 Jan 2023 17:34:49 UTC") },
            { "rse": "RSE-KFSJHMDanvAWbvuSuPpt", "rseblocked": 2, "availability": true, "available_files": 41, "available_bytes": 454, "creation_date": new Date(2020, 5, 3), "last_accessed": new Date("Mon, 02 Jan 2023 23:02:45 UTC") },
            { "rse": "RSE-oMitUdGVsDRTtFMxvVjH", "rseblocked": 0, "availability": true, "available_files": 57, "available_bytes": 445, "creation_date": new Date(2014, 6, 27), "last_accessed": new Date("Fri, 20 Jan 2023 06:55:14 UTC") },
            { "rse": "RSE-eUZNqdwhZswgNOIprtwV", "rseblocked": 0, "availability": true, "available_files": 62, "available_bytes": 537000000000, "creation_date": new Date(2017, 9, 13), "last_accessed": new Date("Sun, 26 Mar 2023 19:23:42 UTC") },
            { "rse": "RSE-tntbucDOMHCyumFBFqYo", "rseblocked": 2, "availability": false, "available_files": 28, "available_bytes": 511000000, "creation_date": new Date(2015, 5, 29), "last_accessed": new Date("Sat, 01 Apr 2023 08:10:53 UTC") },
            { "rse": "RSE-ZqlhSIvxNsGtyTdQRZIA", "rseblocked": 6, "availability": true, "available_files": 93, "available_bytes": 138000, "creation_date": new Date(2020, 12, 11), "last_accessed": new Date("Sun, 01 Jan 2023 07:38:02 UTC") },
            { "rse": "RSE-hjpsRbtERfQiIsRebvAz", "rseblocked": 0, "availability": false, "available_files": 11, "available_bytes": 273, "creation_date": new Date(2016, 4, 28), "last_accessed": new Date("Sun, 02 Apr 2023 10:34:49 UTC") },
            { "rse": "RSE-UoewTMuIuibXCKKnuBuq", "rseblocked": 6, "availability": true, "available_files": 25, "available_bytes": 379000, "creation_date": new Date(2019, 7, 2), "last_accessed": new Date("Mon, 06 Feb 2023 17:58:27 UTC") },
            { "rse": "RSE-gkpFZHCtzGTPkmPwHgTf", "rseblocked": 0, "availability": false, "available_files": 81, "available_bytes": 40000000000, "creation_date": new Date(2019, 6, 5), "last_accessed": new Date("Mon, 03 Apr 2023 18:31:36 UTC") },
            { "rse": "RSE-KcWmXlSIheeGvEOdpjvA", "rseblocked": 4, "availability": true, "available_files": 45, "available_bytes": 3000, "creation_date": new Date(2019, 4, 11), "last_accessed": new Date("Sat, 06 May 2023 12:20:25 UTC") },
            { "rse": "RSE-LncpXbOxPdiEEMjnvCCn", "rseblocked": 0, "availability": false, "available_files": 8, "available_bytes": 186000000000, "creation_date": new Date(2018, 3, 7), "last_accessed": new Date("Sat, 18 Mar 2023 04:01:02 UTC") },
            { "rse": "RSE-JAEJYEGrFPrCIhnUNLsJ", "rseblocked": 0, "availability": false, "available_files": 45, "available_bytes": 975000, "creation_date": new Date(2014, 10, 30), "last_accessed": new Date("Sun, 07 May 2023 12:09:52 UTC") },
            { "rse": "RSE-SPEKeqbgfcJUNhBZPFRP", "rseblocked": 0, "availability": false, "available_files": 87, "available_bytes": 83000, "creation_date": new Date(2016, 4, 12), "last_accessed": new Date("Wed, 11 Jan 2023 08:09:16 UTC") },
            { "rse": "RSE-uBBeMgJNIYvXzOEupQnE", "rseblocked": 2, "availability": true, "available_files": 71, "available_bytes": 971000, "creation_date": new Date(2019, 11, 22), "last_accessed": new Date("Wed, 19 Apr 2023 17:15:56 UTC") },
            { "rse": "RSE-WXGjHXtgtQVzGPHdGoOi", "rseblocked": 0, "availability": false, "available_files": 92, "available_bytes": 535000000, "creation_date": new Date(2020, 2, 22), "last_accessed": new Date("Mon, 16 Jan 2023 08:38:47 UTC") },
            { "rse": "RSE-JJfGPNlDPIIpaGGHqmHg", "rseblocked": 0, "availability": false, "available_files": 7, "available_bytes": 419000000000, "creation_date": new Date(2020, 12, 9), "last_accessed": new Date("Thu, 02 Mar 2023 05:14:29 UTC") },
            { "rse": "RSE-UVdLpSuHGTOtLoKdjXdM", "rseblocked": 5, "availability": false, "available_files": 20, "available_bytes": 54, "creation_date": new Date(2019, 10, 23), "last_accessed": new Date("Mon, 16 Jan 2023 07:31:32 UTC") },
            { "rse": "RSE-FAUyKPKuoQrDPEeWvWiB", "rseblocked": 0, "availability": true, "available_files": 52, "available_bytes": 362000000, "creation_date": new Date(2019, 11, 28), "last_accessed": new Date("Thu, 27 Apr 2023 18:19:12 UTC") },
            { "rse": "RSE-yMeyrUkMNySdCbOiGkLc", "rseblocked": 0, "availability": true, "available_files": 54, "available_bytes": 417000000000, "creation_date": new Date(2018, 3, 27), "last_accessed": new Date("Mon, 01 May 2023 12:37:18 UTC") },
            { "rse": "RSE-jgkuvbAZhPfvEHNbJAED", "rseblocked": 0, "availability": true, "available_files": 43, "available_bytes": 431000000000, "creation_date": new Date(2017, 1, 31), "last_accessed": new Date("Wed, 01 Feb 2023 20:46:54 UTC") },
            { "rse": "RSE-SspXpBHopJiIWYmMaDxb", "rseblocked": 1, "availability": false, "available_files": 85, "available_bytes": 505, "creation_date": new Date(2015, 3, 30), "last_accessed": new Date("Sat, 18 Mar 2023 07:02:49 UTC") },
            { "rse": "RSE-HGjCrsEiLiCPKpGbCXPG", "rseblocked": 0, "availability": false, "available_files": 32, "available_bytes": 506000000, "creation_date": new Date(2015, 3, 27), "last_accessed": new Date("Tue, 03 Jan 2023 03:24:16 UTC") },
            { "rse": "RSE-TJShHqVVtmCouRZavwAy", "rseblocked": 0, "availability": true, "available_files": 61, "available_bytes": 974000000000, "creation_date": new Date(2016, 9, 27), "last_accessed": new Date("Sun, 07 May 2023 17:30:30 UTC") },
            { "rse": "RSE-cCNUcVgcllZIqHNApjUw", "rseblocked": 0, "availability": false, "available_files": 13, "available_bytes": 237000, "creation_date": new Date(2016, 3, 24), "last_accessed": new Date("Tue, 07 Feb 2023 15:44:12 UTC") },
            { "rse": "RSE-DAYLoxvOeegPHLfQxILJ", "rseblocked": 0, "availability": false, "available_files": 78, "available_bytes": 828, "creation_date": new Date(2017, 2, 23), "last_accessed": new Date("Tue, 21 Mar 2023 23:14:16 UTC") },
            { "rse": "RSE-bMrgDCBDzOUdxKPsjOmj", "rseblocked": 0, "availability": false, "available_files": 16, "available_bytes": 610000000, "creation_date": new Date(2020, 1, 9), "last_accessed": new Date("Tue, 21 Mar 2023 09:58:05 UTC") },
            { "rse": "RSE-LLqZmWWFNcqcRgRXFabD", "rseblocked": 0, "availability": true, "available_files": 86, "available_bytes": 43, "creation_date": new Date(2014, 8, 9), "last_accessed": new Date("Thu, 02 Feb 2023 13:30:53 UTC") },
            { "rse": "RSE-JYPaAdVYiEpXINVIHFjR", "rseblocked": 0, "availability": false, "available_files": 8, "available_bytes": 947, "creation_date": new Date(2017, 7, 13), "last_accessed": new Date("Sun, 26 Feb 2023 02:48:20 UTC") },
            { "rse": "RSE-rxwoqIUBkbwMjbUXKeAF", "rseblocked": 0, "availability": false, "available_files": 51, "available_bytes": 225000000000, "creation_date": new Date(2015, 2, 10), "last_accessed": new Date("Tue, 21 Feb 2023 02:02:05 UTC") },
            { "rse": "RSE-DTXXzMhUEHOaeDSqejpj", "rseblocked": 0, "availability": false, "available_files": 62, "available_bytes": 708000000000, "creation_date": new Date(2018, 3, 18), "last_accessed": new Date("Tue, 21 Mar 2023 02:06:00 UTC") },
            { "rse": "RSE-UjLpDOAGkqVbgNiIgzmu", "rseblocked": 0, "availability": true, "available_files": 31, "available_bytes": 961000000000, "creation_date": new Date(2015, 3, 4), "last_accessed": new Date("Sun, 07 May 2023 07:28:07 UTC") },
            { "rse": "RSE-rPjRdyosoklvZnayakpp", "rseblocked": 0, "availability": true, "available_files": 11, "available_bytes": 692000000, "creation_date": new Date(2014, 6, 23), "last_accessed": new Date("Thu, 26 Jan 2023 19:48:35 UTC") },
            { "rse": "RSE-oFRZzsJkemDeblyqRwzR", "rseblocked": 0, "availability": true, "available_files": 79, "available_bytes": 323, "creation_date": new Date(2014, 5, 25), "last_accessed": new Date("Thu, 02 Mar 2023 10:50:03 UTC") },
            { "rse": "RSE-IUREfyAdHcQTjVjVSxwd", "rseblocked": 0, "availability": false, "available_files": 52, "available_bytes": 100000, "creation_date": new Date(2016, 7, 4), "last_accessed": new Date("Wed, 01 Mar 2023 10:29:13 UTC") },
            { "rse": "RSE-oYynlbwwQVGyUNlPEGJD", "rseblocked": 1, "availability": false, "available_files": 74, "available_bytes": 534000, "creation_date": new Date(2019, 6, 12), "last_accessed": new Date("Tue, 07 Mar 2023 12:26:50 UTC") },
            { "rse": "RSE-bDvRVkYOOYoFnkPdZaph", "rseblocked": 0, "availability": true, "available_files": 11, "available_bytes": 680000, "creation_date": new Date(2017, 1, 17), "last_accessed": new Date("Tue, 25 Apr 2023 12:08:24 UTC") },
            { "rse": "RSE-EEzDxGvjAkSzyRwRBBDn", "rseblocked": 0, "availability": false, "available_files": 71, "available_bytes": 621000000, "creation_date": new Date(2020, 3, 14), "last_accessed": new Date("Fri, 05 May 2023 13:24:39 UTC") },
            { "rse": "RSE-mDnUiMuKPFezjfMFzMiy", "rseblocked": 0, "availability": true, "available_files": 63, "available_bytes": 121000000000, "creation_date": new Date(2015, 7, 28), "last_accessed": new Date("Fri, 17 Feb 2023 20:33:04 UTC") },
            { "rse": "RSE-hwliaBqtJKJLaGUlVpSH", "rseblocked": 0, "availability": true, "available_files": 43, "available_bytes": 608, "creation_date": new Date(2016, 9, 28), "last_accessed": new Date("Wed, 03 May 2023 17:30:15 UTC") },
            { "rse": "RSE-jsIPnjtvFeBhkUlpThad", "rseblocked": 0, "availability": false, "available_files": 50, "available_bytes": 328000, "creation_date": new Date(2019, 10, 27), "last_accessed": new Date("Tue, 09 May 2023 15:50:37 UTC") },
            { "rse": "RSE-thzXXZAMpYMHELDHgUGZ", "rseblocked": 0, "availability": false, "available_files": 55, "available_bytes": 170000000000, "creation_date": new Date(2019, 6, 2), "last_accessed": new Date("Tue, 14 Mar 2023 07:02:36 UTC") },
            { "rse": "RSE-SvxVpHrPBisZnGJprPFk", "rseblocked": 0, "availability": false, "available_files": 80, "available_bytes": 136000, "creation_date": new Date(2017, 12, 4), "last_accessed": new Date("Fri, 10 Mar 2023 03:05:05 UTC") },
            { "rse": "RSE-oLtbubYKcxDjLTWboMrQ", "rseblocked": 0, "availability": true, "available_files": 29, "available_bytes": 147000, "creation_date": new Date(2020, 7, 25), "last_accessed": new Date("Tue, 04 Apr 2023 23:15:26 UTC") },
            { "rse": "RSE-iVNGyuXUmPGoiwyTOkDZ", "rseblocked": 0, "availability": true, "available_files": 54, "available_bytes": 287000000000, "creation_date": new Date(2020, 6, 7), "last_accessed": new Date("Mon, 10 Apr 2023 09:27:44 UTC") },
            { "rse": "RSE-cmwRhOvEaROQrhPRFwIl", "rseblocked": 0, "availability": false, "available_files": 69, "available_bytes": 123000, "creation_date": new Date(2016, 9, 9), "last_accessed": new Date("Fri, 13 Jan 2023 17:52:50 UTC") },
            { "rse": "RSE-umJqDEnPEOaPMTiFXHHR", "rseblocked": 0, "availability": true, "available_files": 38, "available_bytes": 515, "creation_date": new Date(2015, 5, 28), "last_accessed": new Date("Thu, 23 Feb 2023 17:31:02 UTC") },
            { "rse": "RSE-kxRGogWVkQLaissJdens", "rseblocked": 0, "availability": false, "available_files": 87, "available_bytes": 280000, "creation_date": new Date(2016, 11, 27), "last_accessed": new Date("Thu, 09 Mar 2023 04:30:48 UTC") },
            { "rse": "RSE-jUIbyyqDpLnDtteruSPa", "rseblocked": 0, "availability": false, "available_files": 20, "available_bytes": 159000, "creation_date": new Date(2018, 8, 1), "last_accessed": new Date("Mon, 24 Apr 2023 13:22:12 UTC") },
            { "rse": "RSE-DVcmcmFXDZTxqzeoYXho", "rseblocked": 0, "availability": true, "available_files": 60, "available_bytes": 659, "creation_date": new Date(2015, 2, 9), "last_accessed": new Date("Wed, 08 Mar 2023 08:15:49 UTC") },
            { "rse": "RSE-nLwFHDBxMNbGoXyalMPd", "rseblocked": 0, "availability": false, "available_files": 77, "available_bytes": 632, "creation_date": new Date(2017, 7, 27), "last_accessed": new Date("Sat, 18 Feb 2023 20:31:48 UTC") },
            { "rse": "RSE-jltqygCgXhwZEirUPUIK", "rseblocked": 0, "availability": true, "available_files": 73, "available_bytes": 92000, "creation_date": new Date(2018, 9, 2), "last_accessed": new Date("Sat, 21 Jan 2023 14:51:37 UTC") },
            { "rse": "RSE-uYmaJxOxxUgREjqKctgm", "rseblocked": 0, "availability": true, "available_files": 5, "available_bytes": 882, "creation_date": new Date(2018, 12, 20), "last_accessed": new Date("Sun, 16 Apr 2023 00:37:44 UTC") },
            { "rse": "RSE-OjWYYhaOcpkhRAvyDWLM", "rseblocked": 4, "availability": true, "available_files": 23, "available_bytes": 156, "creation_date": new Date(2014, 9, 28), "last_accessed": new Date("Wed, 03 May 2023 14:04:08 UTC") },
        ],
        fetchStatus: "idle"
    }
}