#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo 'usage: tools/create-feature-branch <ticketnumber> <branchname>'
    echo
    echo 'examples: tools/create-feature-branch 1234 fancyfeature'
    echo '          tools/create-feature-branch 1234 "my fancy feature"'
    exit 1
fi

echo "Fetching upstream"
git fetch upstream --progress

echo "Switching to main"
git checkout upstream/main -B main
if [ $? != 0 ]; then
    echo "Can't reset and checkout main"
    exit 1
fi

echo "Creating feature branch from main"
git checkout -b feature-$1-${2//[^a-zA-Z0-9]/_} main

echo "Done"