#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo 'usage: tools/create-patch-branch <ticketnumber> <branchname>'
    echo
    echo 'examples: tools/create-patch-branch 1234 fancypatch'
    echo '          tools/create-patch-branch 1234 "my fancy patch"'
    exit 1
fi

echo "Fetching upstream"
git fetch upstream --progress

echo "Switching to main"
git checkout upstream/main -B main
if [ $? != 0 ]; then
    echo "Can't reset and checkout main"
    exit 1
fi

echo "Creating patch branch"
git checkout -b patch-$1-${2//[^a-zA-Z0-9]/_} main

echo "Done"