#!/bin/bash

# install deps & project build done
# control comes here only if install and build goes fine
# assumes 'docs' to be present in the master branch
# assumes 'gh-pages' branch is present

git stash .
git checkout master

# checkout to the gh-pages, reset
# sync the branch with our main

git checkout gh-pages
git reset --hard origin/master

# delete everything on the directory
# ignore the docs folder

find * -maxdepth 0 -name 'docs' -prune -o -exec rm -rf '{}' ';'

# move the docs folder content
# explode in the repository root

mv ./docs/* .

# deletes the git cache
# push the new content to gh-pages

git rm -rf --cache .
git add .
git commit -m "Deploy Storybook to GitHub pages"

# force push to origin/gh-pages
git push origin gh-pages --force
