name: Build Rucio WebUI Component Library & React App
on:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v7

            - name: Install 🔧
              run: |
                  npm install --legacy-peer-deps

            - name: Build Storybook 🔧
              run: |
                  npm run build-storybook

            - name: Build NextJS App 🔧
              run: |
                  npm run build
